### ISSUE TITLE
How to set the background color?

### ISSUE THREAD

**Issue by lhyfst** [kujason/ip_basic#5]
Now my background color is black. However, the further the object is, the whiter the pixels should be. So, it more makes sense if the background color is white.

On the other hand, how to change the relationship between depth and color shade? It also makes sense if the further the object is, the blacker the pixels are.

![depth_000001](https://user-images.githubusercontent.com/29816816/57111942-dac8f800-6cf2-11e9-89c9-c57d031503c2.png)

**Comment by kujason** [comment]
The black pixels in the background are empty, as in there are no values associated with them since there are no LiDAR values to use for depth completion in those areas. If you want them to be filled in with extrapolated values, you can change `extrapolate` to `True`. Or use an empty mask to set those pixels to whichever value you want.

**Comment by lhyfst** [comment]
got it. Thanks!
