### ISSUE TITLE
can this work to improve the detection result of lidar?

### ISSUE THREAD

**Issue by mjjdick** [kujason/ip_basic#6]
Hi, wonderful work! I want to ask, based on your work, the sparsity of lidar can be relieved, and can it imporve the detection performance of lidar? like in avod?

**Comment by kujason** [comment]
We tried feeding the output of the dense depth map into AVOD, but this didn't seem to change results much for cars on KITTI. However, this recent work from Uber (http://www.cs.toronto.edu/~byang/papers/mmf.pdf) shows that depth completion can be useful for 3D detection.

**Comment by mjjdick** [comment]
@kujason I think the depth completion using ip_basic just interpolation in lidar, so it did not provide more information for perception. but the mmf of uber fusing image and lidar information to do depth completion, it more like sensor fusion and provide more information than lidar.

**Comment by kujason** [comment]
@mjjdick Yes, this is pretty much what we concluded as well. However, because of the structure-preserving design of the algorithm (http://kujason.com/notes/depth-completion.html), we have found the dense point clouds to be useful for other tasks like visualization, automatic segmentation, and instance reconstruction (https://arxiv.org/abs/1904.01690)
